name: GitHub Actions Deploy
run-name: ${{ github.actor }} is running Deploy CI 🚀
#on: [push, workflow_dispatch]
on:
  push:
    paths:
      - 'doc/info/**'
  workflow_dispatch:
    
jobs:
  build-docs:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Update OS and get tools
        run: |
          sudo apt-get update
          # Cmucl needs 32-bit libs to run
          sudo apt-get install gcc-multilib
          # texlive for latex so we can build the pdf manual.
          # texlive-plain-generic to get epsf.sty that's needed by the
          # manual.
          sudo apt-get install texlive texlive-plain-generic
      - name: Install cmucl
        # cmucl is installed cmucl in the current directory
        run: |
          wget -nv https://common-lisp.net/project/cmucl/downloads/snapshots/2024/04/cmucl-2024-04-x86-linux.tar.bz2
          mkdir cmucl 
          tar -C cmucl -xjf cmucl-2024-04-x86-linux.tar.bz2
      - name: Configure Maxima
        run: |
          ./bootstrap
          ./configure --enable-cmucl --with-cmucl=$PWD/cmucl/bin/lisp --enable-lang-de --enable-lang-es --enable-lang-pt --enable-lang-pt_BR --enable-lang-ja
      # Need to build maxima so we can build the index.  Without this
      # we fail to build the docs.
      - name: Build Maxima with cmucl
        run: |
          make -C src cmucl
      - name: Setup directories
        run: |
          mkdir _site/docs || true
          mkdir _site/docs/de _site/docs/es _site/docs/pt _site/docs/pt_BR _site/docs/ja || true
      # The user manual needs to be built before the tests are run
      # because there a test for the user manual.
      - name: Build English manual
        # Don't do "make pdf" because that descends the lang
        # directories and pdf doesn't work in some of them.  Thus,
        # just change to each directory and run make appropriately.
        # The Russian docs don't currently work
        run: |
          make -C doc/info html maxima.pdf
      - name: Build German manual
        run: |
          make -C doc/info/de
          make -C doc/info/de pdf
          cp doc/info/de/*.html doc/info/de/maxima.pdf _site/docs/de
      - name: Build Spanish manual
        run: |
          make -C doc/info/es
          make -C doc/info/es pdf
          cp doc/info/es/*.html doc/info/es/maxima.pdf _site/docs/es
      - name: Build Portguese manual
        run: |
          make -C doc/info/pt
          make -C doc/info/pt pdf
          cp doc/info/pt/*.html doc/info/pt/maxima.pdf _site/docs/pt
      - name: Build Brazilian Portguese manual
        run: |
          make -C doc/info/pt_BR
          make -C doc/info/pt_BR pdf
          cp doc/info/pt_BR/*.html doc/info/pt_BR/maxima.pdf _site/docs/pt_BR
      - name: Build Japanese manual
        run: |
          make -C doc/info/ja
          cp doc/info/ja/*.html _site/docs/ja
      - name: Archive user manual
        # uses: actions/upload-artifact@v4
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
