name: GitHub Actions Continuous Integration
run-name: ${{ github.actor }} is running CI 🚀
on: [push]
jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Update OS
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib
      - name: Install sbcl
        run: |
          sudo apt-get install sbcl
      - name: Install ccl64
        run: |
          wget -nv https://github.com/Clozure/ccl/releases/download/v1.12.2/ccl-1.12.2-linuxx86.tar.gz
          tar xzf ccl-1.12.2-linuxx86.tar.gz
      - name: Install cmucl
        run: |
          wget -nv https://common-lisp.net/project/cmucl/downloads/snapshots/2024/04/cmucl-2024-04-x86-linux.tar.bz2
          tar xzf cmucl-2024-04-x86-linux.tar.bz2
      - name: Build Maxima
        run: |
          ./bootstrap
          ./configure --enable-sbcl --enable-ccl64 --with-ccl64=$PWD/ccl/lx86cl64 --enable-cmucl --with-cmucl=bin/lisp
          make
      - name: Run Tests
        run: make check
